- hosts: localhost 
  vars:
    home_dir: /Users/ibalce 
    dotfiles_dir: /Users/ibalce/Documents/projects/dotfiles
  tasks:
  - name: Create ansible directory
    file: path=/etc/ansible state=directory
  - name: Symlink ansible hosts
    file: 
      src: '{{ dotfiles_dir }}/ansible/hosts'
      dest: '/etc/ansible/hosts' 
      state: link
  - name: Symlink config files
    file:
      src: '{{ item.src }}'
      dest: '{{ home_dir }}/{{ item.path }}'
      state: link
    with_filetree:
      - '{{ dotfiles_dir }}/home/'
