- hosts: localhost 
  vars:
    home_dir: "{{ ansible_env.HOME }}" 
    dotfiles_dir: "{{ playbook_dir }}"
    modules_dir: '/etc/ansible/modules'
    brew_utils:
      - bash-completion
      - docker
      - git 
      - maven
      - watch
      - wget
      - zsh
      - zsh-completions
    brew_casks:
      - flux
      - intellij-idea-ce
      - sublime-text
  tasks:
  - name: Create ansible directory
    file: path={{ modules_dir }} state=directory
    become: true
  - name: Symlink ansible hosts
    file: 
      src: '{{ dotfiles_dir }}/ansible/hosts'
      dest: '/etc/ansible/hosts' 
      state: link
    become: true
  - name: Stat oh-my-zsh
    stat:
      path: '{{ home_dir }}/.oh-my-zsh'
    register: zsh
  - name: Cloning oh-my-zsh
    git:
      repo=https://github.com/robbyrussell/oh-my-zsh
      dest='{{ home_dir }}/.oh-my-zsh'
    register: clone_omz
    when: zsh.stat.exists == False
  - name: Creating new ~/.zshrc
    copy:
      src='{{ home_dir }}/.oh-my-zsh/templates/zshrc.zsh-template'
      dest='{{ dotfiles_dir }}/home/.zshrc'
    when: zsh.stat.exists == False and clone_omz is defined and clone_omz|succeeded
  - name: Stat powerline
    stat:
      path: '{{ dotfiles_dir }}/powerline'
    register: powerline
  - name: Cloning powerline fonts
    git:
      repo=https://github.com/powerline/fonts
      dest='{{ dotfiles_dir }}/powerline'
    register: clone_powerline
    when: powerline.stat.exists == False
  - name: Install powerline fonts
    command: '{{ dotfiles_dir }}/powerline/install.sh'
    when: powerline.stat.exists == False and clone_powerline is defined and clone_powerline|succeeded
  - name: Stat spaceship theme
    stat:
      path: '{{ home_dir }}/.oh-my-zsh/themes/spaceship-prompt'
    register: spaceship
  - name: Cloning spaceship theme
    git:
      repo=https://github.com/denysdovhan/spaceship-prompt
      dest='{{ home_dir }}/.oh-my-zsh/themes/spaceship-prompt/'
    register: clone_spaceship
    when: spaceship.stat.exists == False
  - name: Symlink spaceship theme
    file:
      src='{{ home_dir }}/.oh-my-zsh/themes/spaceship-prompt/spaceship.zsh-theme'
      dest='{{ home_dir }}/.oh-my-zsh/themes/spaceship.zsh-theme'
      state=link
    when: clone_spaceship is defined and clone_spaceship|succeeded
  - name: Symlink config files
    file:
      src: '{{ item.root }}{{ item.path }}'
      dest: '{{ home_dir }}/{{ item.path }}'
      state: link
      force: yes
    with_filetree: '{{ dotfiles_dir }}/home/'
    when: item.state == 'file'
  - name: Install homebrew
    command: '{{ dotfiles_dir }}/brew/install.sh'
    register: command_output
    changed_when: "'installed' not in command_output.stdout"
  - name: Ensure homebrew is updated 
    homebrew:
      state: latest
      update_homebrew: yes
  - name: Install with homebrew
    homebrew:
      name: "{{ item }}"
      state: present
    with_items: "{{ brew_utils }}"
  - name: Install with homebrew cask
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items: "{{ brew_casks }}"
  - name: Install docker-machine
    command: '{{ dotfiles_dir }}/docker/machine.sh'
    become: true
    register: command_output
    changed_when: "'installed' not in command_output.stdout"
