- hosts: localhost 
  vars:
    home_dir: "{{ ansible_env.HOME }}" 
    dotfiles_dir: "{{ playbook_dir }}"
    modules_dir: '/etc/ansible/modules'
    brew_utils:
      - bash-completion
      - docker
      - git 
      - maven
      - wget
  tasks:
  - name: Create ansible directory
    file: path={{ modules_dir }} state=directory
    become: true
  - name: Symlink ansible hosts
    file: 
      src: '{{ dotfiles_dir }}/ansible/hosts'
      dest: '/etc/ansible/hosts' 
      state: link
    become: true
  - name: Symlink config files
    file:
      src: '{{ item.src }}'
      dest: '{{ home_dir }}/{{ item.path }}'
      state: link
    with_filetree:
      - '{{ dotfiles_dir }}/home/'
  - name: Install homebrew
    command: '{{ dotfiles_dir }}/brew/install.sh'
    register: command_output
    changed_when: "'installed' not in command_output.stdout"
  - name: Ensure homebrew is updated 
    homebrew:
      state: latest
      update_homebrew: yes
  - name: Install libraries/utils with homebrew
    homebrew:
      name: "{{ item }}"
      state: present
    with_items: "{{ brew_utils }}"
  - name: Install docker-machine
    command: '{{ dotfiles_dir }}/docker/machine.sh'
    become: true
    register: command_output
    changed_when: "'installed' not in command_output.stdout"
