- name: Add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repos }}"
- name: Add keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ apt_keys }}"
  become: true
- name: Ensure apt is updated
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
- name: Set default shell to zsh
  command: "chsh -s $(which zsh)"
